## code to prepare `acs_vars` dataset goes here

library(here)
library(dplyr)

acs_vars <-
  tribble(
    ~variable,    ~description,                                               ~set1, ~set2, ~set3, ~set4, ~set5, ~set6, ~set7, ~dec2010,
    "B11005_001",	"Total households",                                 	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  FALSE,
    "B15002_001",	"Population age 25+",	                                      FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_003",	"Males 25+ w/ no education",	                              FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_004",	"Males 25+ w/ nursery-4th grade as highest education",	    FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_005",	"Males 25+ w/ 5th-6th grade as highest education",	        FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_006",	"Males 25+ w/ 7th-8th as highest education",	              FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_011",	"Males 25+ w/ diploma or alternate as highest education",	  FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_012",	"Males 25+ w/ <1 yr college as highest education",	        FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_013",	"Males 25+ w/ 1+ yrs college w/o degree",	                  FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_014",	"Males 25+ w/ Associate's as highest degree",	              FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_015",	"Males 25+ w/ Bachelor's as highest degree",	              FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_016",	"Males 25+ w/ Master's as highest degree",	                FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_017",	"Males 25+ w/ Professional degree as highest degree",	      FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_018",	"Males 25+ w/ Doctorate as highest degree",	                FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_020",	"Females 25+ w/ no education",	                            FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_021",	"Females 25+ w/ nursery-4th grade as highest education",	  FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_022",	"Females 25+ w/ 5th-6th grade as highest education",	      FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_023",	"Females 25+ w/ 7th-8th as highest education",	            FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_028",	"Females 25+ w/ diploma or alternate as highest education", FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_029",	"Females 25+ w/ <1 yr college as highest education",	      FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_030",	"Females 25+ w/ 1+ yrs college w/o degree",	                FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_031",	"Females 25+ w/ Associate's as highest degree",	            FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_032",	"Females 25+ w/ Bachelor's as highest degree",	            FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_033",	"Females 25+ w/ Master's as highest degree",	              FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_034",	"Females 25+ w/ Professional degree as highest degree",	    FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15002_035",	"Females 25+ w/ Doctorate as highest degree",	              FALSE, FALSE, TRUE,	 FALSE,	TRUE,  FALSE, TRUE,  TRUE,
    "B15003_001",	"Population age 25+",	                                      TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_002",	"People 25+ w/ no education",	                              TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_003",	"People 25+ w/ nursery school as highest education",	      TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_004",	"People 25+ w/ kindergarten as highest education",	        TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_005",	"People 25+ w/ 1st grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_006",	"People 25+ w/ 2nd grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_007",	"People 25+ w/ 3rd grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_008",	"People 25+ w/ 4th grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_009",	"People 25+ w/ 5th grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_010",	"People 25+ w/ 6th grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_011",	"People 25+ w/ 7th grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_012",	"People 25+ w/ 8th grade as highest education",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_017",	"People 25+ w/ diploma as highest education",	              TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_018",	"People 25+ w/ GED or alternate as highest education",	    TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_019",	"People 25+ w/ <1 yr college as highest education",	        TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_020",	"People 25+ w/ 1+ yrs college w/o degree",	                TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_021",	"People 25+ w/ Associate's as highest degree",	            TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_022",	"People 25+ w/ Bachelor's as highest degree",	              TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_023",	"People 25+ w/ Master's as highest degree",	                TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_024",	"People 25+ w/ Professional degree as highest degree",	    TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B15003_025",	"People 25+ w/ Doctorate as highest degree",	              TRUE,  TRUE,	FALSE, TRUE,	FALSE, TRUE,  FALSE, FALSE,
    "B17010_001",	"Total families",	                                          TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B17010_002",	"Families w/ income below poverty level",	                  TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_002",	"Households w/ income under $10k",	                        TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_011",	"Households w/ income $50k-under $60k",	                    TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_012",	"Households w/ income $60k-under $75k",	                    TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_013",	"Households w/ income $75k-under $100k",	                  TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_014",	"Households w/ income $100k-under $125k",	                  TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_015",	"Households w/ income $125k-under $150k",	                  TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_016",	"Households w/ income $150k-under $200k",	                  TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19001_017",	"Households w/ income $200k or more",	                      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B19013_001", "Median household income",                                  FALSE, TRUE,  FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
    "B19113_001",	"Median family income",   	                                TRUE,  FALSE, TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_006",	"Male civilian labor force age 16-19 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_008",	"Unemployed Male civilian labor force age 16-19 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_013",	"Male civilian labor force age 20-21 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_015",	"Unemployed Male civilian labor force age 20-21 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_020",	"Male civilian labor force age 22-24 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_022",	"Unemployed Male civilian labor force age 22-24 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_027",	"Male civilian labor force age 25-29 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_029",	"Unemployed Male civilian labor force age 25-29 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_034",	"Male civilian labor force age 30-34 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_036",	"Unemployed Male civilian labor force age 30-34 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_041",	"Male civilian labor force age 35-44 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_043",	"Unemployed Male civilian labor force age 35-44 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_048",	"Male civilian labor force age 45-54 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_050",	"Unemployed Male civilian labor force age 45-54 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_055",	"Male civilian labor force age 55-59 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_057",	"Unemployed Male civilian labor force age 55-59 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_062",	"Male civilian labor force age 60-61 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_064",	"Unemployed Male civilian labor force age 60-61 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_069",	"Male civilian labor force age 62-64 yrs",	                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_071",	"Unemployed Male civilian labor force age 62-64 yrs",	      FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_074",	"Male labor force age 65-69",	                              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_076",	"Unemployed Male labor force age 65-69 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_079",	"Male labor force age 70-74",	                              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_081",	"Unemployed Male labor force age 70-74 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_084",	"Male labor force age 75+",	                                FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_086",	"Unemployed Male labor force age 75+",	                    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_092",	"Female civilian labor force age 16-19 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_094",	"Unemployed Female civilian labor force age 16-19 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_099",	"Female civilian labor force age 20-21 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_101",	"Unemployed Female civilian labor force age 20-21 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_106",	"Female civilian labor force age 22-24 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_108",	"Unemployed Female civilian labor force age 22-24 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_113",	"Female civilian labor force age 25-29 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_115",	"Unemployed Female civilian labor force age 25-29 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_120",	"Female civilian labor force age 30-34 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_122",	"Unemployed Female civilian labor force age 30-34 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_127",	"Female civilian labor force age 35-44 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_129",	"Unemployed Female civilian labor force age 35-44 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_134",	"Female civilian labor force age 45-54 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_136",	"Unemployed Female civilian labor force age 45-54 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_141",	"Female civilian labor force age 55-59 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_143",	"Unemployed Female civilian labor force age 55-59 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_148",	"Female civilian labor force age 60-61 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_150",	"Unemployed Female civilian labor force age 60-61 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_155",	"Female civilian labor force age 62-64 yrs",	              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_157",	"Unemployed Female civilian labor force age 62-64 yrs",	    FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_160",	"Female labor force age 65-69",	                            FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_162",	"Unemployed Female labor force age 65-69 yrs",	            FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_165",	"Female labor force age 70-74",	                            FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_167",	"Unemployed Female labor force age 70-74 yrs",	            FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_170",	"Female labor force age 75+",	                              FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B23001_172",	"Unemployed Female labor force age 75+",	                  FALSE, FALSE, FALSE, TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B11005_002",	"Households w/ 1+ person <18",                      	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  FALSE,
    "B11005_005",	"Family households w/ single parent & 1+ person <18",       TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  FALSE,
    "B23025_003",	"Civilian labor force age 16+",	                            TRUE,  TRUE,	TRUE,	 FALSE,	FALSE, FALSE, FALSE, FALSE,
    "B23025_005",	"Unemployed civilian labor force age 16+",	                TRUE,  TRUE,	TRUE,	 FALSE,	FALSE, FALSE, FALSE, FALSE,
    "B25003_001",	"Occupied housing units",	                                  TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  FALSE,
    "B25003_002",	"Owner-occupied housing units",	                            TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  FALSE,
    "B25014_001",	"Occupied housing units (tenure/people per room)",	        TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25014_005",	"Owner-occupied housing units with 1.01-1.5 per room",	    TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25014_006",	"Owner-occupied housing units with 1.51-2 per room",	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25014_007",	"Owner-occupied housing units with over 2 per room",	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25014_011",	"Renter-occupied housing units with 1.01-1.5 per room",	    TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25014_012",	"Renter-occupied housing units with 1.51-2 per room",	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25014_013",	"Renter-occupied housing units with over 2 per room",	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25044_001",	"Occupied housing units (tenure/vehicles)",	                TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25044_003",	"Owner-occupied housing units with no vehicle",	            TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25044_010",	"Renter-occupied housing units with no vehicle",	          TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25064_001",	"Median gross rent (cash-paid renter-occupied)",	          TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25077_001",	"Median value of owner-occupied housing units",	            TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "B25088_002",	"Median monthly costs - housing units w/ mortgage",	        TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C17002_001",	"Population w/ known poverty status",	                      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C17002_002",	"People w/ income to poverty level ratio under .5",	        TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C17002_003",	"People w/ income to poverty level ratio .5-.99",	          TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C17002_004",	"People w/ income to poverty level ratio 1-1.24",	          TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C17002_005",	"People w/ income to poverty level ratio 1.25-1.49",	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C24010_001",	"Employed civilians age 16+",	                              TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C24010_003",	"Civilian males age 16+ in white-collar occupations",	      TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  TRUE,  TRUE,  TRUE,
    "C24010_039",	"Civilian females age 16+ in white-collar occupations",	    TRUE,  TRUE,	TRUE,	 TRUE,	TRUE,  FALSE, FALSE, TRUE,
    "C24010_040",	"Civilian females age 16+ in white-collar occupations",	    FALSE, FALSE,	FALSE, FALSE,	FALSE, TRUE,  TRUE,  FALSE
  )

usethis::use_data(acs_vars, overwrite = TRUE)
tools::resaveRdaFiles(here("data", "acs_vars.rda"), compress = "auto")
