---
title: "R Notebook"
output: html_notebook
---

```{r read_in_fips_data}
# https://www2.census.gov/geo/docs/reference/cenpop2010/blkgrp/CenPop2010_Mean_BG.txt
blk_grp_raw <- read.csv("data/CenPop2010_Mean_BG.txt", sep = ",", header = TRUE)
head(blk_grp_raw)
```

```{r pare_down_to_fips_codes_only}
# Pares down to only the fips code data
blk_grp1 <- blk_grp_raw %>%
  dplyr::select(STATEFP, COUNTYFP, TRACTCE, BLKGRPCE)

head(blk_grp1)
```
```{r make_edgelist}
blk_grp2 <- mutate(blk_grp1,
                   STATEFP = stringr::str_pad(STATEFP, width = 2, pad = "0"),
                   COUNTYFP = paste0(STATEFP, stringr::str_pad(COUNTYFP, width = 3, pad = "0")),
                   TRACTCE = paste0(COUNTYFP, stringr::str_pad(TRACTCE, width = 6, pad = "0")),
                   BLKGRPCE = paste0(TRACTCE, as.character(BLKGRPCE))
                   )

el_blkgp <- select(blk_grp2, TRACTCE, BLKGRPCE)%>% 
  rename(from = TRACTCE, to = BLKGRPCE)
el_tract <- select(blk_grp2, COUNTYFP, TRACTCE) %>%
  group_by(COUNTYFP, TRACTCE) %>% 
  filter(row_number() == 1) %>% 
  ungroup() %>% 
  rename(from = COUNTYFP, to = TRACTCE)
el_county <- select(blk_grp2, STATEFP, COUNTYFP) %>%
  group_by(STATEFP, COUNTYFP) %>% 
  filter(row_number() == 1) %>% 
  ungroup() %>% 
  rename(from = STATEFP, to = COUNTYFP)
el <- bind_rows(el_county, el_tract, el_blkgp)
nodes <- tibble(node = c(el$from, el$to)) %>% 
  group_by(node) %>% filter(row_number() == 1) %>% ungroup() %>% 
  mutate(nodeID = row_number())
el2 <- left_join(el, mutate(nodes, from = node), by  ="from") %>% 
  rename(from.ix = nodeID) %>% 
  select(-node) %>% 
  left_join(mutate(nodes, to = node), by = "to") %>% 
  rename(to.ix = nodeID) %>% 
  select(-node)

```

```{r make_graph}
areas <- igraph::graph_from_edgelist(as.matrix(el_county), directed = TRUE)
```



```{r create_vector_of_unique_state_fips_codes}
# Creates a vector of only the unique state fips codes
states <- unique(blk_grp1$STATEFP)
states
```

```{r creates_a_list_object_containing_all_fips_codes}
# Creation of fips_list
fips_list <- lapply(states, function(state) list(state,
                                         lapply(unique(dplyr::filter(blk_grp1, STATEFP == state)$COUNTYFP), function(county) list(county, lapply(unique(dplyr::filter(blk_grp1, STATEFP == state, COUNTYFP == county)$TRACTCE), function(tract) list(tract, unique(dplyr::filter(blk_grp1, STATEFP == state, COUNTYFP == county, TRACTCE == tract)$BLKGRPCE)))))))

# Demonstrates that all the block groups are accounted for
sum(sapply(fips_list, function(state) sum(sapply(state[[2]], function(county) sum(sapply(county[[2]], function(tract) length(tract[[2]])))))))

nrow(blk_grp1)
```

```{r save_fips_list}
save(fips_list, file = "data/fips_list.Rda")
```


```{r}
test_fips_df <- do.call(rbind, lapply(fips_list, function(state) do.call(rbind, lapply(state[[2]], function(county) do.call(rbind, lapply(county[[2]], function(tract) data.frame(state_fips = rep(state[[1]], length(tract[[2]])), county_fips = rep(county[[1]], length(tract[[2]])), tract_fips = rep(tract[[1]], length(tract[[2]])), blk_grp_fips = tract[[2]])))))))

head(test_fips_df)
head(blk_grp1)

str(fips_list)
```
